### ISSUE TITLE
JSX syntax of the form <foo:bar></foo:bar> breaks syntax coloring

### ISSUE THREAD

**Issue by jefedev** [gandm/language-babel#122]
We've using this form of jsx for a while and it looks like the recent release is breaking the syntax coloring. Please refer the attached image for more information.

<img width="1398" alt="jsx syntax color broken" src="https://cloud.githubusercontent.com/assets/9508968/12219985/b481afa8-b70f-11e5-82b3-26a3e0085752.png">

**Comment by gandm** [comment]
I think I removed namespaced components in version 0.3.3 which is pretty old. As far as I could tell they were in the JSX specification but not part of the React spec. I can put them back. As a matter of interest what are you using them for?

**Comment by gandm** [comment]
Babel complains about namespaces so I guess you are using another type of DOM system?
![image](https://cloud.githubusercontent.com/assets/2313237/12220408/0004602a-b769-11e5-8159-97915a2e41bf.png)

**Comment by jefedev** [comment]
I guess we are using some kind of custom transform (to convert <foo:param>) before applying babel transforms and that is probably why babel doesn't complain. I guess it doesn't make much sense to support this form when babel doesn't it support it?

**Comment by gandm** [comment]
Thinking about this I've decided not to include this in the grammar as it isn't Babel nor a React standard. Sorry if this is an issue for you.

**Comment by ssorallen** [comment]
This is namespaced JSX, and it is part of the JSX Specification draft: https://facebook.github.io/jsx/

```
### Elements

JSXNamespacedName :
  JSXIdentifier : JSXIdentifier
```

Would you accept a PR to help implement this?

**Comment by ssorallen** [comment]
As @sebmarkbage [mentioned](https://github.com/facebook/jsx/issues/13#issuecomment-54373080), we use the syntax for our internationalization library and use a transform other than React's bundled JSXTransformer to support the colon-separated namespaces.

Nuclide currently [lists 'language-babel'](https://github.com/facebook/nuclide/blob/master/package.json#L113) in its package-deps to give Nuclide users a JS grammar that supports JSX, but we need to add colon-separated namespaces in order to support our internationalization library's use case.

**Comment by gandm** [comment]
Ok, I'll put the namespace option back in to the grammar. It also appears in other places but I will do it sometime this weekend.

**Comment by ssorallen** [comment]
@gandm Great, thanks a lot. Getting syntax highlighting back will make a lot of developers here happy.
