### ISSUE TITLE
Indent to previous dot

### ISSUE THREAD

**Issue by Nivl** [gandm/language-babel#140]
Hey,

I think it would be useful to allow the code to be indented to the previous dot. So instead of having this:

    MyObject.doSomethin()
    .doSomethingElse()
    .again();

We can have this:

    MyObject.doSomethin()
            .doSomethingElse()
            .again();

What do you guys think about it?

**Comment by gandm** [comment]
At the moment the only specialised on-the-fly indenting I'm doing is React JSX. I have purposely avoided using any form of parser that generates an AST to speed this up. In order to do what you want I would almost certainly need to use an AST generator such as Babel, which I believe would make it inappropriate for doing indenting on-the-fly. It may be better to get the EsLint team to add a rule for this that is `fixable` ( I can't see one that does this ) and then use the linter to reformat your code.

If you have any alternatives for how this might be done I'm all ears.
