### ISSUE TITLE
Folding stuck on multiline string

### ISSUE THREAD

**Issue by jerone** [gandm/language-babel#156]
Consider the following code:

```es6
'use babel'

it('does not fold on multiline strings', () => {
  const foo = `
multiline
  `
})
```

When pressing the fold icon on function `it` it won't fold the whole function:

![es6-folding](https://cloud.githubusercontent.com/assets/55841/13899691/b9033f6c-edf4-11e5-86a4-82b0c693bcd8.png)

**Comment by gandm** [comment]
I think this is an Atom issue. Atom assumes cold folding applies to indented lines. The only control I have over it is a simple regex [here](https://github.com/gandm/language-babel/blob/master/settings/language-babel.json#L5) 

e.g. This issue is still open on Atom https://github.com/atom/atom/issues/3442 and https://github.com/atom/atom/issues/8879

**Comment by jerone** [comment]
Thanks for your answer. Seems indeed an Atom limitation. Issue could be closed as an upstream issue.
