### ISSUE TITLE
JSX Syntax highlighting on Github broken? 

### ISSUE THREAD

**Issue by cozos** [gandm/language-babel#205]
Hey,

I was redirected by Github here: https://github.com/github/linguist/issues/3044 - it seems that JSX Highlighting is broken on Github.

For example: https://github.com/jsx/JSX/blob/master/web/example/xhr/app.jsx

![screen shot 2016-06-07 at 1 42 38 pm](https://cloud.githubusercontent.com/assets/2646862/15875571/7152c1f8-2cbd-11e6-86cb-4c32cefc4c9b.png)

It's certainly possible that the issue is on Github's end and not yours, but just an FYI.

**Comment by gandm** [comment]
I refactored the import/export part of my grammar but that change introduced an issue that has since been fixed.  Github Linguist appears to be using an older version of my package with this bug still present.  Linguist will pull the latest language-babel when they next do a refresh but I don't know when or how often they do that. The last one was 5 days ago. Once that's done it should fix the problem.

I'll close this as it should now work.

**Comment by gandm** [comment]
Actually I was wrong. Github seems to be using language-babel 2.25.1 which is not current but has the fix already applied. I have just tried the Atom editor with that version of my grammar and your source code and it highlights fine - see below. I've posted a query in your linguist issue.

![image](https://cloud.githubusercontent.com/assets/2313237/15882684/207826a2-2d39-11e6-935b-ffbf6b554f84.png)

![image](https://cloud.githubusercontent.com/assets/2313237/15882680/153a789e-2d39-11e6-8919-e57111e4e539.png)

**Comment by cozos** [comment]
Thanks a lot. Appreciate it!

**Comment by pifantastic** [comment]
@cozos appears to still be broken as far as I can tell: https://github.com/jsx/JSX/blob/master/web/example/xhr/app.jsx

![screenshot 2016-06-23 08 33 59](https://cloud.githubusercontent.com/assets/126461/16304947/5121f342-391d-11e6-9b91-b370823d8a9a.png)

Did Github rollback the version they were using? Or is there possibly another bug? Would be awesome to have syntax highlighting back 😄

**Comment by pifantastic** [comment]
bah, sorry, just noticed there was more discussion on the linguist thread.
