### ISSUE TITLE
Incompatible package "react"

### ISSUE THREAD

**Issue by mxstbr** [gandm/language-babel#210]
I just got the new warning introduced in 0069b9207b5f9e66b562804a69bb6bc309ae6d29 that the package "react" is incompatible and was wondering why exactly it is. Would be nice to add a FAQ that explains why certain packages have problems with `language-babel`!

**Comment by gandm** [comment]
'React' monkey patches the atom methods that provide autoindent features. It detects jsx scopes without regard to the grammar being used, so it tries to auto indent jsx that is defined in my grammar. As I also try to do auto indentation using standard atom API's this creates a potential conflict. I also get issues raised here that have nothing to do with my package, e.g. https://github.com/gandm/language-babel/issues/208 

Other packages, that like language-babel, use 'source-preview'  as a service, such as 'source-preview-babel', which has now been deprecated, also contend with language-babel to do the same job. I.e transpile a babel file and display a preview

Hope this answers your question.

**Comment by mxstbr** [comment]
Thanks, that's perfect!

**Comment by nonissue** [comment]
I was having issues with JSX indentation, and ended up here after seeing the message in Atom. Thanks! The `language-babel Auto Indent JSX` works perfectly since I disabled `react`

**Comment by gandm** [comment]
Added reason to notification message.

**Comment by mannyhenri** [comment]
Is there a way to ONLY disable the auto indent on React's package so we can benefit from both packages. I am a heavy user of React and hate to let of any of those two.

**Comment by gandm** [comment]
@mannyhenri you could ask the author of the react package to change the way he does jsx indentation so it is restricted to files that have his grammar enabled, rather than using just a scope test for the file. If he does that then I'm happy to remove the restriction test.

As a matter of interest what features do you use in react that aren't present in this package?

**Comment by eyronic** [comment]
@gandm 
React's auto type snippet isn't present in language-babel. Could you add that or is it unrelated with your package?

**Comment by gandm** [comment]
@eyronic I decided when I developed the package that I wouldn't add snippets to it. A number of reasons for this. 
- For a start, some people like semi-colons, others don't.
- Do I target js snippets, jsx snippets, flow snippets, graphql snippets, angular snippets, etc,, and if so, for which version.
- It is really trivial to create your own snippets and/or copy another package's snippets to your snippet file. E.g. It would take only a minute to copy the react package's snippets to your atom snippets.
- Lastly, there are numerous dedicated snippet packages that address this need. E.g here are some [react snippet packages](https://atom.io/packages/search?utf8=%E2%9C%93&q=react+snippet)

**Comment by evsoul** [comment]
@gandm I'm new to the world of language supporting packages for things like jsx/react, would you say language-babel is good enough for most people working with jsx who don't need snippets? Snippets are nice but syntax support is most important to me.

**Comment by gandm** [comment]
@evsoul I can't comment on it's suitability, that's for you to decide. It is used by some well known developers and is also the recommended JavaScript language package for [nuclide](https://nuclide.io/), Facebook's atom based IDE. As for snippets, see the response above yours, there is a link which shows many packages that offer snippets for JavaScript as well as React.

**Comment by evsoul** [comment]
@gandm fair enough! As long as atom doesn't wonder what the heck a jsx file is, I'm happy! Brackets struggled for a while so I switched from it. I'll give it a go! Thanks for the response.

**Comment by gandm** [comment]
@evsoul you can email at the address on my profile me if you have questions that aren't issues.

**Comment by andywarren** [comment]
HI all, I'm brand new to Atom and React. I'm trying to take a Udemy React course, and I literally have no idea what packages I need in Atom, but I'm getting the same error as stated above. I have the React and Language Babel packages installed. Which is preferred for learning Atom and React? Is there a reason I should choose one over the other? Thanks!

**Comment by gandm** [comment]
@andywarren as the author it is difficult for me to be unbiased. I'm sure that either would meet your needs. 

The react package is a small grammar that extends the native JavaScript grammar package to support JSX. In my opinion the JSX support isn't as robust. 

E.g. react seems to trip up when embedding certain words, punctuation inside JSX such as 
![image](https://cloud.githubusercontent.com/assets/2313237/23634109/8f348aec-02c0-11e7-8773-69edb7aa319f.png)

whereas language-babel works in this case.
![image](https://cloud.githubusercontent.com/assets/2313237/23634531/8fed7f64-02c2-11e7-890e-534e83b21377.png)

React provides snippets and some HTML to JSX forming which you may find useful.

Because react is tied to language-javascript it may it support some additional constructs such as flow syntax, graphql, styled-components, and es2017 etc. Whereas language-babel is a complete grammar.

language-babel provides interfaces to Babel to allow code preview and compilation which may or may not be useful. It also provides a reasonably robust auto indentation of JSX.

Anyway, I'm sure either would be fine for going through your tutorial. I would advise using one or the other but not both.

I think that by end of year this may be academic as Atom will likely adopt a robust incremental AST parsed grammar system, in which case both react and language-babel will become redundant. At least, that is my hope.

Good luck.

**Comment by andywarren** [comment]
@gandm Thanks for the reply and great explanation. With this info I have opted to go with the language-babel package. I actually noticed the examples in your screenshots happening while following my online course. I also never actually got any sort of autocomplete from the react package like I thought. Thanks again!
