### ISSUE TITLE
Feature: HTML autocompleting

### ISSUE THREAD

**Issue by amilajack** [gandm/language-babel#215]
One of the thing i really miss with he react plugin is the jsx autocompletion. Will this be coming to this package?

**Comment by gandm** [comment]
It's already there! It uses auto-complete.
![tag](https://cloud.githubusercontent.com/assets/2313237/16646983/ed3f797c-4424-11e6-88a8-024c0bde5a63.gif)

**Comment by amilajack** [comment]
I should have been more specific. I meant this:

Default html autocompletion:
<img width="306" alt="screen shot 2016-07-07 at 1 30 42 am" src="https://cloud.githubusercontent.com/assets/6374832/16647127/8adbceda-43e2-11e6-9130-6c7e95560332.png">

language-babel autocompletion:
<img width="317" alt="screen shot 2016-07-07 at 1 30 29 am" src="https://cloud.githubusercontent.com/assets/6374832/16647140/9ef5ca42-43e2-11e6-9c60-ac8a65b5aa09.png">

It makes sense that jsx autocompletion includes javascript but it would be nice if jsx autocompletion could only happen inside of react's curly braces.

**Comment by gandm** [comment]
The htnl example uses snippets.When I tried the react package for JSX it doesn't do anything?
 Language babel does auto complete common tags and attributes using autp-complete.
![tag](https://cloud.githubusercontent.com/assets/2313237/16647577/cb486fce-4427-11e6-8afe-f2a46cd5da15.gif)

**Comment by amilajack** [comment]
You're right. I wasn't the react plugin. It was the standard atom snippets. Do you think it would be a good idea to allow those html snippets to be used by language-babel?

**Comment by gandm** [comment]
I've always steered clear of providing snippets in this package as I believe they should be selectable by the user. It is so trivial to create snippets or copy snippets from any package and add them to your own snippets config, or download one of the numerous snippet packages, that it hardly seems worthwhile.

**Comment by gandm** [comment]
Just to be clear. This package provides auto completion for jsx common element names and attributes, only in jsx tags, and only once opened. 

Numerous other packages provide snippets, e.g. the atom JavaScript package provides snippets that are seen inside my grammar because we share a common scope name of `source.js`. This is why I'm not keen on Atom's usage of snippets as you can never know where they emanate from. Also, if you don't use semi colons in your code the standard JavaScript snippets aren't that useful and tend to get in the way.

I'll close this, but feel free to post any comments you might have back here.

**Comment by amilajack** [comment]
That makes sense now. Thanks for explaining.
