### ISSUE TITLE
Lines wrap even when wrap is disabled

### ISSUE THREAD

**Issue by chipit24** [gandm/language-babel#232]
When the language is set to `Babel ES6 JavaScript`, the code editor doesn't respect the Soft Wrap settings; whether or not Soft Wrap is checked, lines still wrap in the code editor.

When the language is switched to just `JavaScript`, wrapping works as expected.

**Comment by gandm** [comment]
Can you provide me with your config.cson atom file?

**Comment by chipit24** [comment]
My `config.cson` file (From Atom > Config...):

```
"*":
  core:
    disabledPackages: [
      "react"
    ]
    packagesWithKeymapsDisabled: [
      "linter-eslint"
      "block-comment-plus"
    ]
    themes: [
      "one-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
  editor:
    fontSize: 12
    scrollPastEnd: true
    showIndentGuide: true
  "exception-reporting":
    userId: "3a1de948-7ac6-969d-a2c5-49d136b44429"
  linter:
    errorPanelHeight: 26
  "linter-eslint":
    useGlobalEslint: true
  welcome:
    showOnStartup: false
```

It had the following at the end
```
".js.jsx.source":
  editor:
    softWrap: true
```

Which I changed to `false` and later removed completely, but it made no difference.

**Comment by gandm** [comment]
lineWrap is an Atom feature that I don't control and should be transparent to language-babel. Can't test this at the moment but will do so later this week.

**Comment by gandm** [comment]
I can't recreate this, but see next paragraph for a possible reason.  I have changed the global setting on/off and the individual package grammar settings for soft wrap and it appears to work OK. As I said, this feature is provided by Atom and not by this package, albeit that any grammar package has this option added to it's config options by Atom. Because of this I have no control over it. 

If you have turned on the default setting for the Atom provided JavaScript package this will also change the behaviour for my package as it shares a subset of my overall scopename. e.g.
If `config.cson` contains
```
".js.source":
  editor:
    softWrap: true
```
which indicates the default JavaScript Package has had it's softwrap turned on,
then as my grammars scope name of  `.js.jsx.source` contains a matching subset of css names it will also wrap! However using the config below will remove any ambiguity, but you said you tried this!
```
".js.jsx.source":
  editor:
    softWrap: false
```

If this is still an issue I suggest you report it to the Atom repo.
