### ISSUE TITLE
Auto-indent in template strings

### ISSUE THREAD

**Issue by adiachenko** [gandm/language-babel#233]
I know `language-babel` package already support auto-indent in JSX. Will it be possible to support auto-indent in html template strings for cases like this (Vue.js and Angular 2 leverage similar template declarations):

```
export default {
  template: `
    <div>
      <h1>
        {{ message }}
      </h1>
    </div>
  `
}
```

**Comment by gandm** [comment]
At the moment I just hand off the parsing of template strings to [Atom's mustache grammar](https://github.com/atom/language-mustache) rather than processing it myself. If I were to provide autoIndent for templates I would have to implement this in my own grammar ( as I do with JSX) but I know very little about Vue.js or Angular. Is there a definitive spec for these packages that show the syntax possibilities - Something like [this JSX spec](http://facebook.github.io/jsx/)?

**Comment by adiachenko** [comment]
I am not sure about Angular but Vue templates is just a normal html that can be put anywhere on the page.

> Vue.js uses a DOM-based templating implementation. This means that all Vue.js templates are essentially valid, parsable HTML enhanced with some special attributes.

[Read more](http://rc.vuejs.org/guide/syntax.html)

It sure seems like a complex task so I don't really expect this to be implemented anytime soon but it would be pretty nice because with introduction of template strings I find myself writing html in this way more and more often and it seems tedious to indent stuff by hand due to muscle memory.
