### ISSUE TITLE
Reflowing comments sometimes eats code

### ISSUE THREAD

**Issue by chmac** [gandm/language-babel#234]
I'm not 100% sure when this does happen, and when it does not. But I've found a reproduction that works for me.

I'm running atom `1.9.9` and language-babel `2.34.0` on OSX. Reproduced on 2 systems, both running the same versions.

This is my example:

```jsx
class Foo extends React.Component {
  // This is a long comment which extends beyond 80 characters and I would like to reflow it
  bar() {
    
  }
}
```

In this example, if I place my cursor on line 2 (the comment) and click Edit > Reflow Selection, lines 1, 2, and 3 get chewed together and reflowed. The result is this:

```jsx
class Foo extends React.Component { // This is a long comment which extends
beyond 80 characters and I would like to reflow it bar() {
    
  }
}
```

While I would expect to get this:

```jsx
class Foo extends React.Component {
  // This is a long comment which extends beyond 80 characters and I would like
  // to reflow it
  bar() {
    
  }
}
```

My workaround is to insert one blank line above and below the comment, then reflow it, and then remove the blank lines. It's not something I've observed in other languages in atom, so I'd guess it somehow relates to this package, but I could well be wrong, I mostly write javascript, so I haven't really tested in any other languages. Please feel free to redirect me to somewhere else if this is the wrong place for the bug report.

**Comment by gandm** [comment]
It seems like a bug in Atom! 

Little bit complex but it appears that [autoflow](https://github.com/atom/autoflow/blob/master/lib/autoflow.coffee#L18) attempts to determine the line that the cursor is on is part of a paragraph. This eventually calls [language-mode](https://github.com/atom/atom/blob/master/src/language-mode.coffee#L196) which eventually determines [here](https://github.com/atom/atom/blob/master/src/language-mode.coffee#L212) that this line isn't a comment line because my grammar doesn't set the whitespace preceeding the // as a comment ( **because it isn't!** ) and therefore determines that this line is part of a paragraph including the line above.

You can see this by starting the comment in column 1 and doing a reflow and it works.

Two solutions:

Report this to the atom repo 
Or
I can set comments of this type to include the whole line as a comment as does the default javascript grammar, even though this incorrect.

**Comment by gandm** [comment]
One further thing you can do is to mark the paragraph yourself. This stops atom trying to find a paragraph, which it seems quite bad at. If you select the whole line/s containing the comments and then reflow it works ok.

**Comment by gandm** [comment]
I decided to scope prefix whitespace on a new lines // comment. This should fix the issue with reflowing // syntax in release 2.35.0.

If myou have other issues with reflow let me know here. As I said above, if you do have issues marking the lines you want to reflow is more robust.

**Comment by chmac** [comment]
@gandm Awesome, thanks. I was winding up to suggest that as a stop gap, and I'll open an issue on atom linking here with your detailed explanation of what the issue is and what the fix might be. Thus, maybe the atom folks will fix it upstream, and then this change will no longer be necessary.

Thanks for the speedy reply and speedier resolution, will be wonderful to reflow without hesitation! 👍
