### ISSUE TITLE
switch statement case indentation

### ISSUE THREAD

**Issue by kwall2004** [gandm/language-babel#236]
switch statement case blocks are not indented and neither are return statement blocks when they are inside the case:

![image](https://cloud.githubusercontent.com/assets/19229852/18053273/9f7213a4-6dcc-11e6-8104-128641254ec3.png)

**Comment by gandm** [comment]
Wow! You certainly like inline JS inside JSX :laughing: It's not a criticism by the way.  

I'll have a look at this. I'll have to be careful that I don't end up with a JS indentor, rather than a JSX indentor.   Do you use for/while loops,, as these would need to be indented. I have a unexposed feature in the code that allows certain line indentations to be relaxed in a positive manner, i.e. I can allow some lines to have additional indentation. Would this be something that could help?

**Comment by kwall2004** [comment]
Yes, I've noticed that feature and it would help here.

**Comment by gandm** [comment]
Can you try 2.36.0. It now has auto-indentation for inline JSX containing switch/case/default and for/while loops.

**Comment by kwall2004** [comment]
Awesome!  Thank you, sir!
