### ISSUE TITLE
Async methods on objects that are array elements

### ISSUE THREAD

**Issue by daltones** [gandm/language-babel#257]
Here's an example:
![captura de tela de 2016-09-29 18-38-02](https://cloud.githubusercontent.com/assets/5603632/18973497/1368173a-8674-11e6-9d14-dd15ee8106ec.png)

As you can see if an object is an array element, all nested objects are affected too.

We're almost there :smile:

**Comment by gandm** [comment]
Um!  It was designed to work if you put the curly brace immediately after the array open. `var foo = [{` but that isn't what you want. This is more tricky than you'd imagine because I've tried to be spec correct and only allow method's inside object literals. Unfortunately, flow complicates this because I have to be aware what side of the assignment operator the object definition is, as this affects the parsing. Oh for being able to maintain state in TextMate grammars!!

**Comment by gandm** [comment]
Actually, this turned out to be quite trivial. Released on 2.42.3.

**Comment by daltones** [comment]
Ah! Glad it was easy. Thank you!
