### ISSUE TITLE
add taggedTemplateGrammar support in .languagebabel

### ISSUE THREAD

**Issue by gre** [gandm/language-babel#276]
Hi,

I noticed this great feature: https://github.com/gandm/language-babel/issues/242#issuecomment-256016824

but I also noticed it is missing in https://github.com/gandm/language-babel/blob/8ba30a7548e177595cff7211a88e1e62281221e0/lib/transpiler.coffee#L7
so it's not possible yet to define such .languagebabel :

```json
{
  "taggedTemplateGrammar": ["GLSL:source.glsl"]
}
```

<img width="444" alt="screen shot 2016-10-25 at 15 57 54" src="https://cloud.githubusercontent.com/assets/211411/19688917/dfab4f2c-9acb-11e6-8219-4b499b308562.png">

**Comment by gandm** [comment]
No, your correct, it's an Atom wide settin stored in your editor's config.cson, as it's not possible (well, not easily) to do it on a project basis. The reason is the array of tags/scopes defined in `taggedTemplateGrammar` actually creates a new grammar file, prefixed ttl, that is loaded by language-babel. If this were created on a project basis then opening files in different projects within the same editor would overwrite the grammar that other files were using. 

What scenario would you envisage using this setting in one project but not in another?

**Comment by gre** [comment]
oh ok, I thought it was linked to this project!
Actually it's more that I was thinking to "provide a basic config" for people forking / using my project. But maybe I should just document on how you can enable the syntax enhancement ;)

So I guess it's not possible to define it, I'll have to tell people to manually paste this in the conf?

**Comment by gandm** [comment]
I'll have to think about this. I guess I could read a .languagebabel  property and merge it into the config.cson property, as after the first merge the grammar wouldn't be recreated. However even a merge isn't trivial as it is just a string array, so it makes comparisons somewhat imprecise.

**Comment by gandm** [comment]
I can't think of a simple way to ensure that deleted or changed templates definitions inside a project are removed/updated from the global config. I think i'll have to stick with what I have now. I.e. user controls it.

**Comment by gre** [comment]
ok sure, no worries ;) thanks
