### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by SumeetR** [gandm/language-babel#280]
Hey,

I found a bug with the new release of your atom package.

So if I try to move the 'Bug' tag into the React tag, using the keyboard shortcut (control+command+up), the indentation on the 'p' tag is lost. Happens if I move out stuff out of a tag too, coming out completely flat.

<img width="436" alt="screen shot 2016-11-02 at 16 33 57" src="https://cloud.githubusercontent.com/assets/6136978/19935396/3625f3f8-a11a-11e6-8ac1-8004a92ae069.png">

<img width="428" alt="screen shot 2016-11-02 at 16 34 05" src="https://cloud.githubusercontent.com/assets/6136978/19935400/39a34788-a11a-11e6-93ef-07663bfb1415.png">

Anyway, thanks for the package, it's been very useful.
Sumeet

**Comment by gandm** [comment]
I haven't changed anything that might affect this. Sometimes the atom installer screws up. Can you uninstall language-Babel and reinstall? Also, are you using autoIndentJsx?

**Comment by SumeetR** [comment]
I'm not using autoIndentJsx and wasn't using it before either (if it existed). I disabled all the other packages and re-installed language-babel but I still get the issue.

Any ideas?

**Comment by gandm** [comment]
I just tried it and had no issues. I've seen this before and it always turns out to be an issue with Atom and the installer. Also, the setting 'autoIndentJsx' has been there for ages and is quite a robust means of aligning/reformatting JSX. See the readme.

Anyway, I suggest uninstalling language-babel, quitting Atom, removing the cache directory inside the ~/.atom directory, apl install language-babel, and then restarting Atom.

What OS? Atom version?

**Comment by SumeetR** [comment]
I'm running OS X 10.11.6 with the Atom 1.11.2.

Followed your steps but I still get the issue with a fresh copy of Atom. Strange.

Do you need any more info?

**Comment by gandm** [comment]
Unless my package's autoindentjsx is turned on then all indentation of this type is done by atom and not the package. Atom just aligns copied text using the previous lines indent. Maybe you inadvertently changed an atom setting. Please check the atom editor settings for two options - auto indent and auto indent on paste. These are the atom settings that control this behaviour.

**Comment by gandm** [comment]
Also, let me have copy of your config.cson please.

**Comment by SumeetR** [comment]
My config.cson is the following (added [blank] to sensitive info) as I nuked the previous .atom folder without making a backup...

```
"*":
  core:
    audioBeep: false
    closeEmptyWindows: false
    destroyEmptyPanes: false
    hideVcsIgnoredFiles: true
    openEmptyEditorOnStart: false
    projectHome: "/Users/[blank]/Projects/"
    telemetryConsent: "no"
  editor:
    fontSize: 11
    showIndentGuide: true
  "exception-reporting":
    userId: "[blank]"
  welcome:
    showOnStartup: false
```

I am having an issue with Atom after re-installing it where the .gitignore files aren't being hidden in the tree view. Not sure if this issue is related to the one we are discussing.

Anyway, thanks for the help, really need to get this working!
Sumeet

**Comment by gandm** [comment]
I can't explain this. As I said, I only do indentation if my package setting `autoIndentJsx` is on and only for JSX blocks. I presume this also happens when moving non indented JavaScript into an indented bock and also if another language is used for the file? It seems like some form of core Atom issue!  I've tried this on atom 1.11.2 and 1.12.x-beta and it works fine unless I turn off the Atom core editor settings I mentioned previously.

e.g. Atom autoindents here when inserting new text, which is what you are doing when selecting a bloack and moving it. https://github.com/atom/atom/blob/d84bce9022822700ca5d35a680a9a6383eabd160/src/selection.coffee#L381

**Comment by gandm** [comment]
I'm going to close this as I don't believe it to be a package issue.
