### ISSUE TITLE
Syntax highlighting breaks on export type from

### ISSUE THREAD

**Issue by steelbrain** [gandm/language-babel#285]
<img src="https://cloud.githubusercontent.com/assets/4278113/20054168/80c5ab78-a490-11e6-96e1-c68d0b754ddc.png">

Language-Babel v2.47.0 on macOS Sierra

**Comment by gandm** [comment]
Didn't know this was possible as it isn't mentioned in the flow docs that I can see. Doesn't `export { FileError } from 'someFIle'` do the same? Flow should presumably know this is a type def, and it's also more aligned to the spec. I'm guessing you actually use this form of syntax and it works?

**Comment by steelbrain** [comment]
The main difference between `export` and `export type` is that the latter is flow-only and is stripped entirely on compile. So if you do a `export type` to a npm-ignored file or a non-existent in npm bundle file, it won't give an error as there'll be no `require` for it.

Also just a note that I am using that syntax on both ESLint and Flow and both recognize it completely :)

**Comment by gandm** [comment]
Yes I understand, that which is why I made my edit above, realising that flow wouldn't strip it. There are no test specs showing this syntax form nor any doc showing it, so I haven't supported it. It's the problem of having flow but no actual specs for it's syntax! It makes logical sense, but plenty of things in JavaScript make sense but don't work. Hence some TC39 improvements to import and export  Providing it works i'll add it.
