### ISSUE TITLE
Is embedded graphql highlighting working as intended?

### ISSUE THREAD

**Issue by ryancole** [gandm/language-babel#298]
I'm using `language-babel` along with `oceanic-next` syntax theme. I seem to recall (a few months back) that the `Relay.QL` syntax highlighting worked differently. I'm coming back to a project that uses Relay and GraphQL and now feel like the highlighting of this embedded GraphQL fragment does not look how it should.

Below is a screenshot of how my embedded GraphQL fragments look, using the `Relay.QL` prefix ...

![untitled](https://cloud.githubusercontent.com/assets/484801/20452191/eb745b94-adc9-11e6-93ed-ff47fd411e9f.png)

It sort of looks inconsistent. The `fragment on Viewer` portion is one color while the remainder of the fragment is another. Also, it's all white, etc. I seem to recall it having a bit more of a consistent color scheme.

I do not explicitly have the `language-graphql` package installed, but installing it doesn't seem to change anything.

Is this working as intended? Thanks!

**Comment by gandm** [comment]
Nothing has changed in graphql support since its inception in September using release V3.39.0 and a small change in V2.40.0. I just had a look at what oceanic-next looked like in this release, shown below.

Looking at the CSS scopes, they all look correct. I don't use `language-graphql` but I do have another package `language-graphql-lb` that allows viewing of .gql files. But this isn't required for embedded templates. 

![image](https://cloud.githubusercontent.com/assets/2313237/20453415/f0475d54-ae1b-11e6-9c22-d2871cd4129c.png)
