### ISSUE TITLE
No Longer supported?

### ISSUE THREAD

**Issue by fayimora** [gandm/language-babel#302]
>Please note that this package is no longer supported.

I just spotted this in the README but I see @gandm still pushing commits. Clarification on that statement will appreciated 😃

**Comment by dodekeract** [comment]
@fayimora @gandm probably doesn't want to fully commit to this project anymore. I think it's more like a disclaimer that it's not a high priority project.

**Comment by gandm** [comment]
I will attempt to fix issues and add grammar support for new features (such as private class fields) if at all possible. However, I can't guarantee that these will be done in a timely manner, hence the support notice. If a new grammar should appear that is better supported I may choose to deprecate this package.

**Comment by timneutkens** [comment]
@gandm maybe a notice saying `PR's are welcome` is a good thing in this case, since right now it looks like it's deprecated and that's a waste of all time that has been put into it 😄 I will add it if you agree 👍

**Comment by dodekeract** [comment]
PR's what? The suspense is killing me!

**Comment by jayands** [comment]
@dodekeract That's actually proper, if somewhat "dated" grammar that has its basis in handwriting. in order to ensure clarity when pluralising acronyms and initialisms, people would often put periods between the all-capital sequence `$(Boolean OR)` use an apostrophe after said sequence. It's kind of fallen out of use since the proliferation of type as the primary interpersonal communication medium, but it's still not *wrong*, per se.

For example, you might see in a handwritten letter the phrases `C.D.s`, `DVD's`, and `V.H.S.'s`, assuming the letter was about someone's collection of "vintage" technology.

**Comment by timneutkens** [comment]
@jayands haha great sample on English grammar 😄 I'm dutch... I sometimes tend to forget that it's PRs in english... 👍 In dutch we have words like `pictures` => `foto's` it's basically multiplying.

**Comment by michalczaplinski** [comment]
I would also strongly support changing the wording in the notice, because it makes it seem like the package is abandoned completely. I initially did not install it until a colleague pointed out to me that it is not the case and I believe many people will stop reading and move on after seeing the notice :)
