### ISSUE TITLE
Losing syntax highlighting with this example

### ISSUE THREAD

**Issue by zyklus** [gandm/language-babel#312]
I'm not sure if this belongs here, or with Babel or some other package, but hoping you can point me in the right direction.

This (`<T>` is flow-annotation) highlights perfectly:

```js
const foo = <T>() => 42;
```

But if you put a line-break anywhere between the function name and arrow, syntax highlight breaks for the entire rest of the file.

**Comment by gandm** [comment]
It's because `const foo = <T>` looks like JSX to the regex parser and anything following would be considered as plain text until some more JSX is found. In fact, syntax highlighting would work again if a closing JSX statement were to be found; `</T>` in your example.

I'm unable to fix this due to limitations of the Atom grammar features. Because grammars are TextMate based they can't look ahead to following lines and determine if an arrow exists.  If the arrow is on the same line then I can determine that this is not JSX but a flow generic function.

If this is a pattern you require then you could use flow [comment syntax](https://flowtype.org/docs/syntax.html#comment-syn)
