### ISSUE TITLE
Can i make a block contents  to a scope ?

### ISSUE THREAD

**Issue by ccqgithub** [gandm/language-babel#336]
in the react native component, the style can not auto complete
```
const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: 'rgb(245,245,245)'
  }
})
```

i see `JavaScript Tagged Template Literal Grammar Extensions` in doc，but i do not  want use   Template Literal here, can i use `({` and `})` to replace the Template Literal ` `` ` ?

just like : 
```
(StyleSheet\.create\(\{.+\}\))":source.css
```

**Comment by gandm** [comment]
No I'm afraid that won't work as it needs to be a backtick following the regex.

**Comment by ccqgithub** [comment]
oh tks, do u have some idea to help me autocomplete-css in the babel language like this:
```
const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: 'rgb(245,245,245)'
  }
})
```

**Comment by gandm** [comment]
Couple of issues. In order for me to display that as CSS I would have to do something similar to how I handled Tagged Template Extensions. However, even if I did this work neither language-css nor my own css grammar would parse the above as it isn't CSS, and because it isn't CSS no autocomplete would work. 

It is of course possible but would require some significant effort to do this, which I will not be undertaking. Someone would have to write something similar to my extension grammars, rewrite my CSS or Atom's language-css to understand the object literal CSS format, in particular the use of quoted strings and then rewrite either my auto complete CSS or Atoms autocomplete-css. 

I'm going to close this.
