### ISSUE TITLE
syntax highlighting fails on multi-line arrow functions

### ISSUE THREAD

**Issue by mgmcdermott** [gandm/language-babel#342]
<img width="290" alt="screen shot 2017-03-22 at 4 32 22 pm" src="https://cloud.githubusercontent.com/assets/8161781/24219438/2a21237c-0f1d-11e7-97cc-207a3f06066c.png">

Also note that the syntax highlighting doesn't work if the const does not have flow types.

**Comment by gandm** [comment]
Yes this is an issue that I can't fix. I can't read ahead to find out that this is a function because the arrow appears on a later line. This is a limitation of textmate grammars. Therefore I don't know that the bracket contents are arguments. The Atom team are working on a proper grammar parser based upon incremental AST that should be able to parse this type of construct. You can see their progress at github.com/tree-sitter.

**Comment by gandm** [comment]
It's a great shame as prettier makes this type of syntax format more likely. I could probably improve it slightly but I always run into edge cases. With tree-sitter promising super fast parsing and a robust AST I think that textmate grammars will be a thing of the past. That is why I'm a bit reluctant to do too much work in this area. I may revisit this given some time to see if any small changes can improve the result.
FYI VSCode also has similar problems. 
 
![image](https://cloud.githubusercontent.com/assets/2313237/24222095/d3af1766-0f48-11e7-8c8c-cc7c5cc470dd.png)

**Comment by gandm** [comment]
Actually I forgot I made some changes in the middle of last year that make this possible! I just pushed 2.57.1 that should fix this. One thing I can't do is scope the const var name as a function as I explained earlier.

@mgmcdermott Can you check that the flow types are correctly highlighted and that the body return is now correct? For reference what is the theme you are using?

**Comment by gandm** [comment]
@mgmcdermott I think you are using oceanic-next. If so then this is the best I can do. In my grammar the function block, including its body, has a meta scope of `meta.function.js` whereas the multiline arrow func has no such scope. Again this is because the the parameter args have already been parsed by the time the arrow is encountered.

oceanic-next scopes any class=function/variable./readwrite as orange. 

![image](https://cloud.githubusercontent.com/assets/2313237/24247758/d4ab91e0-0fc4-11e7-91a5-d661c11faead.png)

**Comment by mgmcdermott** [comment]
Sorry for the delay @gandm but I appreciate the quick response. This is a major improvement for me. Thanks.
