### ISSUE TITLE
[Flow] Type representation for function params differs when are setted in multiple lines

### ISSUE THREAD

**Issue by lgraziani2712** [gandm/language-babel#361]
When params are in one line:

![image](https://cloud.githubusercontent.com/assets/15050200/25781408/48a080f6-3310-11e7-926d-82e7ba09b5d6.png)

When are in multiple lines:

![image](https://cloud.githubusercontent.com/assets/15050200/25781414/5b1176fa-3310-11e7-80e8-a04cd93c8dce.png)

Thank you :)

**Comment by gandm** [comment]
Thanks. Fixed  2.59.1

**Comment by lgraziani2712** [comment]
Hello @gandm. I'm still experiencing this issue.

Tested on v2.59.1 and v2.60.0.

**Comment by gandm** [comment]
Seems OK for me
![image](https://cloud.githubusercontent.com/assets/2313237/25826649/80297020-343f-11e7-95aa-b73f08306338.png)

**Comment by lgraziani2712** [comment]
Array<number> needs to be always in light blue when they are type definition. Instead, they are colored like they were part of the code.

**Comment by gandm** [comment]
OK I misunderstood your original issue. I thought you were saying that the multi-line was correct. I missed the second Array being different.

**Comment by lgraziani2712** [comment]
Sorry I didn't explain it well.

I'll do next time :)

**Comment by gandm** [comment]
OK I've reverted to my prior handling of this plus a few minor tweaks. 

The bad news is I don't think I'll be able to fix the issue in your second gif above. I have no way of knowing that `const a=(` is a arrow function's parameters until I get to the `=>`, by which time it is too late. In the first example I can determine that in probability a `const a=(value,` is an arrow function because of the `,` It could of course be a comma separated expression list but is more unlikely ( I feel).

**Comment by lgraziani2712** [comment]
Oh, OK good to know.

Thank you @gandm!

**Comment by lgraziani2712** [comment]
I can confirm that with the new update this is fixed.

Congrats @gandm !! 😊🎉

**Comment by gandm** [comment]
@lgraziani2712 Thanks. It's not quite right (not scoped as function parameters) but it's the best I can do.
