### ISSUE TITLE
Arrow function definitions split over multiple lines not identified

### ISSUE THREAD

**Issue by dane-johnson** [gandm/language-babel#366]
An arrow function definition that has newlines in the arguments list is not identified as a function in the syntax highlight.

![screen shot 2017-05-15 at 10 01 04 am](https://cloud.githubusercontent.com/assets/10768827/26064064/763ed7ba-3955-11e7-82a9-e6b3539bec7d.png)

**Comment by gandm** [comment]
Because grammars can't read ahead i have no idea this is an arrow function at the point of entry. For certain comma delimited arrow functions I make a 'probable guess' that it is an arrow function coming up but I've already parsed the name of the variable before I make this determination. So in your example above the arguments are scoped as function parameters but the variable holding the function is denoted as a storage var.

![image](https://cloud.githubusercontent.com/assets/2313237/26068131/65fd8e8e-3994-11e7-8733-cbd1bbf7d028.png)

I will have a look to see if anything can be done to improve this but I'm not sure it is possible without undesirable side effects.

**Comment by dane-johnson** [comment]
I noticed a similar bug in the Coffeescript grammar as well

**Comment by gandm** [comment]
I can't fix this due to limitations beyond my control so i'll close this issue.

**Comment by dodekeract** [comment]
@gandm This issue comes up from time to time — perhaps we should add a "sticky" issue for this and flag it as "upstream bug"?
