### ISSUE TITLE
TODO highlighting not working

### ISSUE THREAD

**Issue by breandr** [gandm/language-babel#37]
When setting syntax to Babel ES6 Javascript, syntax highlighting from https://atom.io/packages/language-todo does not work.

**Comment by breandr** [comment]
Cross issue https://github.com/atom/language-todo/issues/32

**Comment by kevinsawicki** [comment]
Comment patterns need to use `begin`/`end` patterns instead of `match` patterns to enable injection grammars (like language-todo) to match in between.

These need to be adjusted: https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json#L388-L401

You can follow the pattern used recently in language-go to support this: https://github.com/atom/language-go/commit/e5180ac1faab5007f036f716de4650dc75f68d16

**Comment by gandm** [comment]
@breandr Can you give me an example of the js TODO  where this is an issue so I can test. Thanks

**Comment by breandr** [comment]
It doesn't work in any scenario for me. So creating an empty file with `//TODO: todo is not highlighted` should be sufficient.
