### ISSUE TITLE
Flow type generics on functions are incorrectly detected as JSX

### ISSUE THREAD

**Issue by johnhaley81** [gandm/language-babel#388]
Hi! Thanks for all your hard work on this great package.

I noticed that when a function with 

1) flow type generics
2) parameters split up over multiple lines

this package incorrectly detects the generic as a JSX tag and puts the `JSXNested` class on it and then that style leaks through to the rest of the document and things just go crazy afterwards.

Ex:
![image](https://user-images.githubusercontent.com/867780/28144438-58d5f462-6720-11e7-9bb6-54370d965f81.png)

If the generic is removed things are styled correctly:
![image](https://user-images.githubusercontent.com/867780/28144478-8b0981c4-6720-11e7-996c-6c9e5614902e.png)

Or if the parameters are all on the same line things are ok:
![image](https://user-images.githubusercontent.com/867780/28144493-a55be058-6720-11e7-8d89-48a301fedeb4.png)

**Comment by gandm** [comment]
Thanks for the report. Yes I am aware of this. It is because it is ambiguous if the is a generic or JSX until latter lines are parsed and TextMate grammars can't look ahead. I could make the assumption that <T>( is a function and not JSX but this would be no more than a 'guess' but I think it is a more likely occurrence so I will modify accordingly.

In the meantime `<T,>(` is still valid flow and fixes the problem.

**Comment by gandm** [comment]
2.67.0 should fix this.

**Comment by johnhaley81** [comment]
Confirmed fixed on my end That was crazy fast. Thanks @gandm!
