### ISSUE TITLE
Highlight issue with object inside string interpolation

### ISSUE THREAD

**Issue by whmountains** [gandm/language-babel#433]
The following snippet of code doesn't highlight as I'd expect:

```js
const styles = {
  transform: `translateY(${{
    3: '0',
    2: '-0.5rem',
    1: '-1rem',
  }[layer]})`,
}
```

Here's a screenshot from my editor to show what I mean:

![screen shot 2017-10-26 at 9 21 14 am](https://user-images.githubusercontent.com/8680147/32052560-0a894d9c-ba2f-11e7-86aa-ed411efe5be0.png)

* The last curly brace on line 7 should be white.
* The colons and commas on lines 8-10 should be white.
* The square brackets and the first curly brace on line 11 should be white.

It's not a big deal, only slightly annoying.  I'm reporting it so you can decide whether it's worth your time to fix it.

Thanks!

**Comment by gandm** [comment]
This is really an issue for the theme. The white color above is really just the default color of any text not maked up. The green coming through inside a template is because this is the default for a string. In your theme there is no css color for a brace. 

I markup my braces as either `meta.brace.curly.js` or `meta.brace.curly.litobj.js` so you can amend your atom `styles.less` to add something like:
```less
.syntax--source.syntax--js.syntax--jsx{
  .syntax--brace.syntax--curly   {
    color: #abb2bf;
  }
}
```

gives

![image](https://user-images.githubusercontent.com/2313237/32059133-194ce6d4-ba63-11e7-96c3-e0584b693bdf.png)

**Comment by gandm** [comment]
Same goes for square braces and comma and probably all other punctuation.

**Comment by whmountains** [comment]
Thanks for clarifying.
