### ISSUE TITLE
Is it possible to use Babel Language for .ts and .tsx files?

### ISSUE THREAD

**Issue by IljaDaderko** [gandm/language-babel#445]
I was trying to scout this library and atom docs in order to see if I can use `language-babel` grammar syntax for `.ts` and `.tsx` files as I find it much better than one provided by atoms typescript package.

I can't seem to find a setting or a way to set babel as my default though, hence wanted to know if it is possible?

**Comment by gandm** [comment]
I'm not sure what you mean by
> atoms typescript package

Do you mean the official one at https://github.com/atom/language-typescript.  I think this should be pretty good as it is written and maintained by Microsoft. The Atom team has ported it and are also working on other initiatives that are better suited to a TypeScript workflow. See https://github.com/atom/language-typescript and https://atom.io/packages/ide-typescript 

If you still want to use this grammar then you could try modifying config.cson to force .ts files to use my grammar - https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539

**Comment by IljaDaderko** [comment]
@gandm its good, but your grammar has better support for things like styled-components and in general feels more pleasing.
I tired:

```
core:
    customFileTypes:
      "source.tsx": [
        "language-babel"
      ],
```

but it doesn't seem to have any effect, I guess there is something else I need to specify besides `language-babel` ?

**Comment by gandm** [comment]
It should be
```
  core:
    customFileTypes:
      'source.js.jsx': [
        'ts'
        'tsx'
      ]
```

**Comment by IljaDaderko** [comment]
Did the trick, unfortunately it messes with a lot of other plugins like file-icons / tslint :/ but thank you for your time

**Comment by vitexikora** [comment]
Thats a very stupid solution - it is basically saying, that all ts/tsx files should be treated as JSX files. Not only for this plugin, but for all plugins! So this cripples `file-icons`, but most importantly `eslint`, which treats it like a JS file and fires errors on TS features.
I have manually edited the source code of the plugin (`language-babel/grammars/Babel language.json`) so that `scopeName` is now `"source.js.jsx, source.ts.tsx"` and added `ts` and `tsx` to `fileTypes`. 

**Now it works like charm!** 

However, is there a better solution? Can this be edited in the atom config maybe? The docs vaguely say to "Use the standard ATOM interface to enable it for other file types" but do not specify how - I hope they did not mean the stupid file type override.. Currently it is working for me, but I cannot update the plugin, or sync my Atom config across other devices seamlessly (the manual edit wont be synced).

**Comment by saadq** [comment]
Hey @vitexikora, I tried doing what you mentioned above, but my `.ts`/`.tsx` files still open with the `TypeScriptReact` syntax highlighting after reloading.


<img width="1904" alt="config" src="https://user-images.githubusercontent.com/5678694/145753301-f5329a63-d64e-4e44-acad-df26440de33b.png">

Additionally, I'm not getting any of the functionality from the `language-babel` package such as the autocompletion for styled-components.

<img width="1904" alt="autocomplete" src="https://user-images.githubusercontent.com/5678694/145753296-9a169872-9fca-4feb-a0b5-f8f1457ec34c.png">

I've already confirmed that my changes to the file did go through when I looked at the available grammars and see my `source.ts.tsx` changes there, although they have no effect.

<img width="599" alt="Screen Shot 2021-12-12 at 11 40 37 PM" src="https://user-images.githubusercontent.com/5678694/145753532-b639044e-41b9-4e69-929e-51121a634ac0.png">


---

I know it's been a couple of years since your tip above, but if you or anyone has any context on this it would be extremely appreciated!

**Comment by vitexikora** [comment]
It is possible that my old fix is not working anymore with the current version of this plugin or Atom. 
I am sorry, but I cannot help you, because I did a switch from Atom to VSC about a year ago and I am so happy since then. Especially for TS, it is just so much more streamlined.
