### ISSUE TITLE
Support constants

### ISSUE THREAD

**Issue by alxtz** [gandm/language-babel#447]
In the official language-javascript package, variables declared with `const` or in all caps would mark the `syntax--constant` class
![](https://i.imgur.com/5kF8XwC.png)
![](https://i.imgur.com/WZ475eN.png)
Much syntax themes support this `syntax--constant` class, I think it would be awesome to have this added ( or give some advice about how I can contribute to this )

**Comment by gandm** [comment]
In the first example `language-babel` does this
![image](https://user-images.githubusercontent.com/2313237/32405739-efe460d6-c162-11e7-9c70-8deda421b3ab.png)

In the second case the problem lies with having multiple coma separated vars. `language-javascript` breaks like this.
![image](https://user-images.githubusercontent.com/2313237/32405781-9f7bd272-c163-11e7-880b-9852c55e6b7c.png)
This issue has been raised before. See [here](https://github.com/gandm/language-babel/issues/315)
