### ISSUE TITLE
Arrow function syntax highlight broken when breakdown function params

### ISSUE THREAD

**Issue by vdhieu** [gandm/language-babel#464]
Hi, I found this error when I'm pass object destructor as param in arrow function. 

I'm using Atom: 1.23.1 language-bable: 2.81.1

![image](https://user-images.githubusercontent.com/12120998/34239786-524d5496-e63c-11e7-8ea3-50adf866f6a4.png)

**Comment by gandm** [comment]
`setInputValue` should be scoped as a function and `rNum` etc should be scoped as parameters but aren't.  This is because current Atom grammars can't look ahead to following lines, so I can't detect the `=>` which indicates it is a function. Therefore I can't fix it. 

Apart from that, I can't see anything else wrong?
