### ISSUE TITLE
Highlighting broken in places when using JSX inside <script> tags

### ISSUE THREAD

**Issue by chaitanyathengdi** [gandm/language-babel#498]
I've just installed language-babel v2.85.0 in Atom.

Some keywords just appear white when using JSX code inside a HTML file and `<script type='text/babel'>` tags.
Here's a comparison:
This is with plain HTML highlighting:
![jsx_html_issue_html](https://user-images.githubusercontent.com/14993220/39757622-0c1dc35e-52eb-11e8-8356-745c4a329aba.png)

The JS part is fine, but obviously Atom doesn't know what to do about the JSX, so that's white.

Here's a JS-vs-HTML comparison of the Babel highlighter:
![jsx_html_issue_babel](https://user-images.githubusercontent.com/14993220/39757693-4d9387f6-52eb-11e8-957e-0148408d28ca.png)

As seen on the right, the `const`s, function statements and `ReactDOM.render` statement are white when they shouldn't be.
Why is this?

P.S. You seem to mention in some other issue that the grammars for this are taken from Sublime, and when I noticed this versus what Sublime is showing (I'm doing the [free React bootcamp](https://tylermcginnis.com/free-react-bootcamp/) where Tyler uses Sublime), similar highlighting is present there as well.

**Comment by gandm** [comment]
That's because `language-html` embeds the `language-javascript` code when a `<script` tag is encountered. That's outside my control. I think [Kent Dodds did a version of the html grammar](https://atom.io/packages/language-html-babel) that fixed this but I haven't tried it
Yes this was originally a fork for babel-sublime but it is nothing like it now.
