### ISSUE TITLE
How activate flow?

### ISSUE THREAD

**Issue by mazzy89** [gandm/language-babel#52]
Should I install anything else to activate flow grammar? I put `/* @flow */` at the beginning of file but there is no check of the file

**Comment by gandm** [comment]
Language-Babel just supports flow typing for syntax highlighting, it doesn't interact with flow itself. Babel will strip out any flow typing and effectively replaces the  old Facebook JSX Transform tool and is now the Facebook recommended way of generating pure JavaScript code.

If you need to flow check a file you need to put the `/* @flow */` at the top of the file and then setup flow so that when a source file is saved it is flow checked, either by using the flow cli or flow server - http://flowtype.org/docs/new-project.html#_ A better way may be to use the Facebook packages for Atom - i.e. nuclide. See http://nuclide.io/docs/flow/ for more info.
