### ISSUE TITLE
Support for .jsx extension

### ISSUE THREAD

**Issue by seekshiva** [gandm/language-babel#69]
I have a codebase where JSX code is stored using .jsx extension, and `webpack` converts various entrypoints to the corresponding js file on save. 

The 'Transpile On Save' is a great feature. I don't have to refresh the page, and check if something is broken. But it only seems to be working on files with .js extension and not the ones with .jsx extension.

Would you recommend renaming all .jsx files to .js? Or will language-babel support .jsx extension in the future?

**Comment by gandm** [comment]
.jsx files are supported by default. If another grammar also supports .jsx and/or has been enabled for .jsx files prior then the other grammar tends to take precedence. Either disable the other grammar or ensure my grammar is selected. Look at the bottom right status bar to see the grammar selected. Click it if incorrect.

**Comment by gandm** [comment]
The read me describes this
Usage

By default the language-babel package will detect file types  .js , .babel , .jsx  and  es6 . Use the standard ATOM interface to enable it for other file types. This provides a grammar that scopes the file in order to colour the text in a meaningful way. If other JavaScript grammars are enabled these may take precedence over language-babel. Look at the bottom right status bar indicator to determine the language grammar of a file being edited. language-babel will be shown as  Babel ES6 JavaScript

**Comment by seekshiva** [comment]
Thanks!

I'm sorry I missed that.

**Comment by seekshiva** [comment]
This is awesome. Thanks for creating the project :)
