### ISSUE TITLE
Error saving .js file about base.blacklist

### ISSUE THREAD

**Issue by jtsom** [gandm/language-babel#98]
Trying to save a JS file (Ember .js specifically), I'm seeing a Babel V6.0.16 Transpiler Error: "Unknown option: base.blacklist" for every js file save.

**Comment by gandm** [comment]
I have just released v1.0.0 of language-babel which supports Babel v6. Babel 6 is not compatible with Babel v5. If you still want to use Babel v5 or use the old .babelrc file contents you will need to install an older copy of language-babel. I.e. apm install language-babel@0.15.13 

The readme has more info or leave me a comment below. Thanks

**Comment by jtsom** [comment]
I don't have any specific .babelrc file - I have no idea where that base.blacklist is - there's nothing in this project like that.

**Comment by gandm** [comment]
Restart Atom and see if that fixes it. If not then I need some background.

Do you only use the grammar and don't want to use the Babel features? If so can you make sure the package settings for `language-babel` have `Transpile On Save` is turned off. 

Can you give me your Atom config available from Atom menu's.

**Comment by jtsom** [comment]
Ah, restarting seems to have fixed things. Have to figure out why my .js files aren't being defaulted to this anymore, but I'll check my settings. (it also looks like it defaulted to not transpile if there's not a .babelrc file, nor display the success message on save) Thanks.

**Comment by gandm** [comment]
Yeah I changed some of the defaults. 

If you are using the babel transpile features in `language-babel` then you may want to look at the readme section. Babel V6 is very different to V5 - with V5 it did quite a lot out-of-the-box whereas V6 needs presets or plugins loaded otherwise it does nothing. See these blogs http://babeljs.io/blog/2015/10/31/setting-up-babel-6/ and http://babeljs.io/blog/2015/10/29/6.0.0/ 

Reopen this issue if you have any other issues.
